---
- hosts: all
  remote_user: vagrant
  become: yes
  tasks:

    - name: Install java
      apt:
        update_cache: yes
        name: openjdk-7-jdk
        state: present

    - name: Set java home
      lineinfile:
        path: /etc/default/bigtop-utils
        line: export JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk-amd64
        create: yes

    - name: Download CDH5 package
      get_url:
        url: http://archive.cloudera.com/cdh5/one-click-install/precise/amd64/cdh5-repository_1.0_all.deb
        dest: /vagrant
        force_basic_auth: yes

    - name: Install CDH5 repository
      apt:
        deb: /vagrant/cdh5-repository_1.0_all.deb

    - name: Add Cloudera repository
      apt_key:
        url: http://archive.cloudera.com/cdh5/ubuntu/precise/amd64/cdh/archive.key

    - name: Update apt packages
      apt:
        update_cache: yes
        force_apt_get: yes
    
    - name: Install hadoop
      apt: 
        name: hadoop-0.20-conf-pseudo 
        state: latest

    - name: Format the file system
      command: sudo -u hdfs hdfs namenode -format

    - name: Start HDFS services
      service:
        name: "{{ item }}"
        state: started
      loop:
        - hadoop-hdfs-datanode
        - hadoop-hdfs-namenode
        - hadoop-hdfs-secondarynamenode

    - name: Create /tmp directory
      command: sudo -u hdfs hadoop fs -mkdir -p /tmp

    - name: Set permissions for /tmp directory
      command: sudo -u hdfs hadoop fs -chmod -R 1777 /tmp

    - name: Create the MapReduce system directories
      command: sudo -u hdfs hadoop fs -mkdir -p /var/lib/hadoop-hdfs/cache/mapred/mapred/staging

    - name: Set permissions for MapReduce system directories
      command: sudo -u hdfs hadoop fs -chmod 1777 /var/lib/hadoop-hdfs/cache/mapred/mapred/staging

    - name: Change owner for MapReduce system directories
      command: sudo -u hdfs hadoop fs -chown -R mapred /var/lib/hadoop-hdfs/cache/mapred

    - name: Start MapReduce services
      service:
        name: "{{ item }}"
        state: started
      loop:
        - hadoop-0.20-mapreduce-jobtracker
        - hadoop-0.20-mapreduce-tasktracker

    - name: Create user directories for vagrant user
      command: sudo -u hdfs hadoop fs -mkdir -p /user/$USER

    - name: Change directory owner for vagrant user
      command: sudo -u hdfs hadoop fs -chown $USER /user/$USER
